#! /bin/sh

set -e

if [ "$1" = "configure" ]; then
    update-alternatives \
      --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/termit 20 \
      --slave /usr/share/man/man1/x-terminal-emulator.1.gz x-terminal-emulator.1.gz /usr/share/man/man1/termit.1.gz
fi

#DEBHELPER#

exit 0


